routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\EventController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [EventController::class, 'index'])->name('welcome.events');
Route::post('/events/store', [EventController::class, 'store'])->name('store.events');
Route::get('/events/contact', [EventController::class, 'contact'])->name('contact.events');
Route::get('/events/create', [EventController::class, 'create'])->middleware('auth')->name('create.events');
Route::get('/events/edit{id}', [EventController::class, 'edit'])->middleware('auth')->name('edit.events');
Route::put('/events/update/{id}', [EventController::class, 'update'])->middleware('auth')->name('update.events');
Route::delete('/events/{id}', [EventController::class, 'destroy'])->middleware('auth')->name('destroy.events');
Route::get('/events/{id}', [EventController::class, 'show'])->name('show.events');


Route::get('/dashboard', [EventController::class, 'dashboard'])->middleware('auth')->name('dashboard.events');

Route::post('/events/join/{id}', [EventController::class, 'joinEvent'])->middleware('auth')->name('join.events');
Route::delete('/events/leave/{id}', [EventController::class, 'leaveEvent'])->middleware('auth')->name('leave.events');

app/Models/Event.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Event extends Model
{
    use HasFactory;
    protected $table = 'events';
    protected $fillable = ['title', 'description', 'city', 'private', 'image','items', 'date', 'time'];
    
    protected $casts = [
        'items' => 'array',
    ];

    protected $dates = ['date'];

    protected $time = ['time'];

    //relation one to many
    public function user(){
        return $this->belongsTo('App\Models\User');
    }

    public function users(){
        return $this->belongsToMany('App\Models\User');
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Fortify\TwoFactorAuthenticatable;
use Laravel\Jetstream\HasProfilePhoto;
use Laravel\Sanctum\HasApiTokens;
use App\Models\Event;

class User extends Authenticatable
{
    use HasApiTokens;
    use HasFactory;
    use HasProfilePhoto;
    use Notifiable;
    use TwoFactorAuthenticatable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
        'two_factor_recovery_codes',
        'two_factor_secret',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    protected $appends = [
        'profile_photo_url',
    ];

    //relation one to many
    public function events(){
        return $this->hasMany('App\Models\Event');
    }

    public function eventsAsParticipants(){
        return $this->belongsToMany('App\Models\Event');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/EventController.php
<?php

namespace App\Http\Controllers;

use App\Models\Event;
use Illuminate\Http\Request;
use App\Models\User;

class EventController extends Controller
{
    public function index()
    {

        $search = request('search');

        if($search){
            $events = Event::where([
                ['title', 'like', '%'.$search.'%']
            ])->get();
        } else {
            $events = Event::all();
        }
       

        return view('welcome', [
            'events' => $events,
            'search' => $search
        ]);
    }

    public function create()
    {
        return view('events.create');
    }

    public function store(Request $request)
    {

        $event = new Event;

        $event->title = $request->title;
        $event->date = $request->date;
        $event->time = $request->time;
        $event->city = $request->city;
        $event->private = $request->private;
        $event->description = $request->description;
        $event->items = json_encode($request->items);

        //Image validation to Upload
        if ($request->hasFile('image') && $request->file('image')->isValid()) {

            $requestImage = $request->image;
            $extension = $requestImage->extension();
            $imageName = md5($requestImage->getClientOriginalName() . strtotime("now")) . "." . $extension;

            $request->image->move(public_path('img/events'),  $imageName);

            $event->image = $imageName;
        }

        //preenchendo user_id automatically

        $user =  auth() -> user();
        $event->user_id = $user->id;

        //save
        $event->save();

        return redirect()->route('welcome.events')->with('msg', 'Evento criado com sucesso');
    }

    public function show($id)
    {
        $event = Event::findOrFail($id);

        $user = auth() -> user();
        $hasUserJoined = false;

        if($user){
            $userEvents = $user->eventsAsParticipants->toArray();
            foreach($userEvents as $userEvent){
                if($userEvent['id'] == $id){
                    $hasUserJoined = true;
                }
            }
        }

        $eventOwner =  User::where('id', $event->user_id)->first()->toArray();

        return view('events.show', [
            'event' => $event,
            'eventOwner' => $eventOwner,
            'hasUserJoined' => $hasUserJoined
        ]);
    }

    public function dashboard(){
        $user = auth()->user();
        $events = $user->events;

        $eventsAsParticipants = $user->eventsAsParticipants;
        
        return view('events.dashboard', [
            'events' => $events,
            'eventsAsParticipants' => $eventsAsParticipants
        ]); 
    }

    public function destroy($id){
        Event::findOrFail($id)->delete();
        return redirect()->route('dashboard.events')->with('msg', 'Evento deletado com sucesso');
    }

    public function edit($id){

        $user = auth()->user();
        $event = Event::findOrFail($id);

        if($user->id != $event->user_id){
            return redirect()->route('dashboard.events');
        }
        return view('events.edit', ['event' => $event]);
    }

    public function update($id, Request $request){
        Event::findOrFail($request->id)
        ->update($request->all());

        return redirect()->route('dashboard.events')->with('msg', 'Evento editado com sucesso');
    }

    public function joinEvent($id){
        $user = auth()->user();
        $user->eventsAsParticipants()->attach($id);
        $event = Event::findOrFail($id);

        return redirect()->route('dashboard.events')->with('msg', 'Sua presença está confirmada no evento'. $event->title);
    }

    public function leaveEvent($id){
        $user = auth()->user();
        $user->eventsAsParticipants()->detach($id);
        $event = Event::findOrFail($id);

        return redirect()->route('dashboard.events')->with('msg', 'Candidatura encerrada em: '. $event->title);
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/contact.blade.php
@extends('layout.main')
@section('title', 'HDC - contato')
@section('conteudo')
  <h1>Página de contatos</h1>
  <a href="/">Voltar para Home</a>
@endsection

resources/views/events/create.blade.php
@extends('layout.main')
@section('title', 'HDC - criar evento')
@section('conteudo')
  <div id="event-create-container" class="col-md-6 offset-md-3">
    <h1>Crie o seu evento</h1>
    <form action="{{route('store.events')}}" method="post" enctype="multipart/form-data">
      @csrf
      <div class="form-group">
        <label for="image">Imagem do evento</label>
        <input type="file" name="image" id="image" class="form-control-file" required>
      </div>
      <div class="form-group">
        <label for="title">Evento</label>
        <input type="text" class="form-control" id="title" name="title" placeholder="Nome do Evento" required>
      </div>
      <div class="form-group">
        <label for="date">Data do evento</label>
        <input type="date" class="form-control" id="date" name="date" required>
      </div>
      <div class="form-group">
        <label for="time">Horário do evento</label>
        <input type="time" class="form-control" id="time" name="time" required>
      </div>
      <div class="form-group">
        <label for="title">Cidade</label>
        <input type="text" class="form-control" id="city" name="city" placeholder="maracanaú" required>
      </div>
      <div class="form-group">
        <label for="private">O evento é privado?</label>
        <select class="form-control" name="private" id="private" required>
          <option value="0">Não</option>
          <option value="1">Sim</option>
        </select>
      </div>
      <div class="form-group"> 
        <label for="description">Descrição</label>
        <textarea name="description" id="description" class="form-control" placeholder="Explicar o evento" required></textarea>
      </div>
      <div class="form-group">
        <label for="title">Infraestrutura do Evento</label>
        <div class="form-group">
          <div class="form-group">
            <input type="checkbox" name="items[]" value="cadeira"> Cadeiras
          </div>
          <div class="form-group">
            <input type="checkbox" name="items[]" value="palco"> Palco
          </div>
          <div class="form-group">
            <input type="checkbox" name="items[]" value="openbar"> Openbar
          </div>
          <div class="form-group">
            <input type="checkbox" name="items[]" value="openfood"> Openfood
          </div>
          <div class="form-group">
            <input type="checkbox" name="items[]" value="brindes"> Brindes
          </div>
        </div>
      </div>
      <input type="submit" class="btn btn-primary" value="Criar Evento">
    </form>
  </div>
@endsection

resources/views/events/dashboard.blade.php
@extends('layout.main')
@section('title', 'Dashboard')
@section('conteudo')
<div class="col-md-10 offset-md-1 dashboard-title-container">
    <h1>Meus Eventos</h1>
</div>
<div class="col-md-10 offset-md-1 dashboard-events-container">
    @if(count($events) > 0)
    <table class="table">
        <thead>
            <th scope="col">#</th>
            <th scope="col">Nome</th>
            <th scope="col">Participantes</th>
            <th scope="col">Ações</th>
        </thead>
        <tbody>
            @foreach ($events as $event)
                <tr>
                    <td>{{ $loop->index + 1 }}</td>
                    <td>
                        <a href="/events/{{$event->id}}">{{ $event->title}}</a>
                    </td>
                    <td>{{count($event->users)}}</td>
                    <td>
                        <a class="btn btn-info edit-btn" href="{{route('edit.events', $event->id)}}">
                            <ion-icon name="create-outline"></ion-icon>
                            Editar
                        </a>
                        <form action="{{route('destroy.events', $event->id)}}" method="POST">
                            @csrf
                            @method('DELETE')
                            <button class="btn btn-danger delete-btn" type="submit">
                                <ion-icon name="trash-outline"></ion-icon>
                                Deletar
                            </button>
                        </form>
                    </td>  
                </tr>
            @endforeach
        </tbody>
    </table>
    @else
    <p>Você ainda não cadastrou eventos. <a href="{{route('create.events')}}">Criar Evento</a></p>
    @endif
</div>
<div class="col-md-10 offset-md-1 dashboard-title-container">
    <h1>Eventos que estou participando</h1>
</div>
<div class="col-md-10 offset-md-1 dashboard-events-container">
    @if (count($eventsAsParticipants) > 0)
        <table class="table">
            <thead>
                <th scope="col">#</th>
                <th scope="col">Nome</th>
                <th scope="col">Participantes</th>
                <th scope="col">Ações</th>
            </thead>
            <tbody>
                @foreach ($eventsAsParticipants as $event)
                    <tr>
                        <td>{{ $loop->index + 1 }}</td>
                        <td>
                            <a href="/events/{{$event->id}}">{{ $event->title}}</a>
                        </td>
                        <td>{{count($event->users)}}</td>
                        <td>
                            <form action="{{route('leave.events', $event->id)}}" method="POST">
                                @csrf
                                @method('DELETE')
                                <button class="btn btn-danger delete-btn" type="submit">
                                    <ion-icon name="trash-outline"></ion-icon>
                                    Sair do evento
                                </button>
                            </form>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <p>Você ainda não está participando de nenhum evento, <a href="{{route('welcome.events')}}">Ver eventos disponíveis</a></p>
    @endif
</div>
@endsection

resources/views/events/edit.blade.php
@extends('layout.main')
@section('title', 'HDC - Editando evento')
@section('conteudo')
  <div id="event-create-container" class="col-md-6 offset-md-3">
    <h1>Editando: {{$event->title}}</h1>
    <form action="{{route('update.events', $event->id)}}" method="post" enctype="multipart/form-data">
      @csrf
      @method('PUT')
      <div class="form-group">
        <label for="image">Imagem do evento</label>
        <input type="file" name="image" id="image" class="form-control-file">
        <img src="/img/events/{{ $event->image }}" alt="{{$event->title}}" class="img-preview">
      </div>
      <div class="form-group">
        <label for="title">Evento</label>
        <input type="text" class="form-control" id="title" name="title" placeholder="Nome do Evento" value="{{$event->title}}" required>
      </div>
      <div class="form-group">
        <label for="date">Data do evento</label>
        <input type="date" class="form-control" id="date" name="date" value="{{$event->date->format('Y-m-d')}}" required>
      </div>
      <div class="form-group">
        <label for="time">Horário do evento</label>
        <input type="time" class="form-control" id="time" name="time" value="{{$event->time}}" required>
      </div>
      <div class="form-group">
        <label for="title">Cidade</label>
        <input type="text" class="form-control" id="city" name="city" placeholder="maracanaú" value="{{$event->city}}" required>
      </div>
      <div class="form-group">
        <label for="private">O evento é privado?</label>
        <select class="form-control" name="private" id="private" required>
          <option value="0">Não</option>
          <option value="1" {{$event->private == 1 ? "selected='selected'" : ""}}>Sim</option>
        </select>
      </div>
      <div class="form-group"> 
        <label for="description">Descrição</label>
        <textarea name="description" id="description" class="form-control" placeholder="Explicar o evento" required>{{$event->description}}"</textarea>
      </div>
      <div class="form-group">
        <label for="title">Infraestrutura do Evento</label>
        <div class="form-group">
          <div class="form-group">
            <input type="checkbox" name="items[]" value="cadeira"> Cadeiras
          </div>
          <div class="form-group">
            <input type="checkbox" name="items[]" value="palco"> Palco
          </div>
          <div class="form-group">
            <input type="checkbox" name="items[]" value="openbar"> Openbar
          </div>
          <div class="form-group">
            <input type="checkbox" name="items[]" value="openfood"> Openfood
          </div>
          <div class="form-group">
            <input type="checkbox" name="items[]" value="brindes"> Brindes
          </div>
        </div>
      </div>
      <input type="submit" class="btn btn-primary" value="Editar Evento">
    </form>
  </div>
@endsection

resources/views/events/show.blade.php
@extends('layout.main')
@section('title', $event->title)
@section('conteudo')
  <div class="col-md-10 offset-md-1">
    <div class="row">
      <div id="image-container" class="col-md-6">
        <img src="/img/events/{{$event->image}}" alt="{{$event->title}}" class="img-fluid">
      </div>
      <div id="info-container" class="col-md-6">
          <h1>{{$event->title}}</h1>
          <p class="event-city">
            <ion-icon name="location-outline"></ion-icon>
            {{$event->city}}
          </p>
          <p class="events-participants">
            <ion-icon name="people-outline"></ion-icon>
            {{count($event->users)}} Participantes
          </p>
          <p class="event-owner">
            <ion-icon name="star-outline"></ion-icon>
            {{$eventOwner['name']}}
          </p>
          @if (!$hasUserJoined)
            <form action="{{route('join.events', $event->id)}}" method="POST">
              @csrf
              <a href="{{route('join.events', $event->id)}}" 
              class="btn btn-primary"  
              id="event-submit"
              onclick="event.preventDefault();
              this.closest('form').submit();">
                Confirmar Presença
              </a>
            </form>
          @else
           <p class="already-joined-msg">
            Você já está cadastrado nesse evento
           </p>
          @endif
          <h3>O evento conta com:</h3>
          <ul id="items-list">
            @foreach (json_decode($event->items) as $item)
              <li>
                <ion-icon name="play-outline"></ion-icon>
                <span>
                  {{$item}}
                </span>
              </li>
            @endforeach
          </ul>
      </div>
      <div class="col-md-12" id="description-container">
        <h3>Sobre o evento:</h3>
        <p class="event-description">{{$event->description}}</p>
      </div>
    </div>
  </div>
@endsection

resources/views/layout/main.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>@yield('title')</title>
        <!--Google Fonts-->
        <link href="https://fonts.googleapis.com/css2?family=Roboto" rel="stylesheet">
        <!--Bootstrap 5.0 da Aplicação-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
        <!--JS da Aplicação-->
        <script type="text/javascript" src="{{asset('js/script.js')}}"></script>
        <!--Css da Aplicação-->
        <link rel="stylesheet" href="{{asset('css/style.css')}}">
    </head>
    <body>
        <header>
          <nav class="navbar navbar-expand-lg navbar-light">
            <div class="collapse navbar-collapse" id="navbar">
              <a href="/" class="navbar-brand">
                <img src="{{asset('img/logo-hdc.png')}}" alt="HDC Events">
              </a>
              <ul class="navbar-nav">
                <li class=" nav nav-item">
                  <a href="{{route('welcome.events')}}" class="nav-link">Eventos </a>
                </li>
                @auth
                <li class="nav-item">
                  <a href="{{route('create.events')}}" class="nav-link">Criar Eventos</a>
                </li>
                <li class="nav-item">
                  <a href="{{route('dashboard.events')}}" class="nav-link">Meus Eventos</a>
                </li>
                <li class="nav-item">
                  <form action="/logout" method="post">
                    @csrf
                    <a href="/logout" 
                      class="nav-link" 
                      onclick="event.preventDefault();
                      this.closest('form').submit();">
                      Sair
                    </a>
                  </form>
                </li>
                @endauth
                @guest
                  <li class="nav-item">
                    <a href="/login"" class="nav-link">Entrar</a>
                  </li>
                  <li class="nav-item">
                    <a href="/register" class="nav-link">Cadastrar</a>
                  </li>
                @endguest
              </ul>
            </div>
          </nav>
        </header>
        <main>
          <div class="container-fluid">           
            <div class="row">
              @if (session('msg'))
                  <p class="msg">{{session('msg')}}</p>
              @endif
              
              @yield('conteudo')
            </div>
          </div>
        </main>
        <footer>
          <p>HDC Events &copy; 2022</p>
        </footer>
      <!--JavaScript Bundle BOOTSTRAP-->
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
      <!--ION icons CDN-->
      <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
      <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
  </body>
</html>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        @livewireStyles

        <!-- Scripts -->
        @vite(['resources/css/app.css', 'resources/js/app.js'])
    </head>
    <body class="font-sans antialiased">
        <x-jet-banner />

        <div class="min-h-screen bg-gray-100">
            @livewire('navigation-menu')

            <!-- Page Heading -->
            @if (isset($header))
                <header class="bg-white shadow">
                    <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
                        {{ $header }}
                    </div>
                </header>
            @endif

            <!-- Page Content -->
            <main>
                {{ $slot }}
            </main>
        </div>

        @stack('modals')

        @livewireScripts
    </body>
</html>

resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Scripts -->
        @vite(['resources/css/app.css', 'resources/js/app.js'])
    </head>
    <body>
        <div class="font-sans text-gray-900 antialiased">
            {{ $slot }}
        </div>
    </body>
</html>

resources/views/policy.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-jet-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $policy !!}
            </div>
        </div>
    </div>
</x-guest-layout>

resources/views/terms.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-jet-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $terms !!}
            </div>
        </div>
    </div>
</x-guest-layout>